[project]
name = "mangadex"
version = "0.1.0"
description = "A synchronous Python client for the MangaDex API."
readme = "README.md"
requires-python = ">=3.11"
license = "MIT"
license-files = ["LICENSE"]
keywords = ["api", "client", "manga", "mangadex"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Topic :: Software Development :: Libraries",
]
dependencies = [
    "httpx>=0.28.1",
    "tqdm>=4.67.0",
]

[project.urls]
Repository = "https://github.com/princessmiku/MangaDexClient"
Issues = "https://github.com/princessmiku/MangaDexClient/issues"

[build-system]
requires = ["setuptools>=77"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]
include = ["mangadex*"]
namespaces = false

[tool.semantic_release]
version_toml = ["pyproject.toml:project.version"]
version_variables = ["src/mangadex/__init__.py:__version__"]
build_command = "python -m build --sdist --wheel ."

[tool.semantic_release.changelog]
exclude_commit_patterns = [
    '''chore(?:\([^)]*?\))?: .+''',
    '''ci(?:\([^)]*?\))?: .+''',
    '''refactor(?:\([^)]*?\))?: .+''',
    '''style(?:\([^)]*?\))?: .+''',
    '''test(?:\([^)]*?\))?: .+''',
]
